// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/yumekiti/eccSchoolApp-api/domain"
)

// NewsUsecase is an autogenerated mock type for the NewsUsecase type
type NewsUsecase struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0
func (_m *NewsUsecase) Get(_a0 *domain.User) ([]*domain.News, error) {
	ret := _m.Called(_a0)

	var r0 []*domain.News
	if rf, ok := ret.Get(0).(func(*domain.User) []*domain.News); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.News)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewNewsUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewsUsecase creates a new instance of NewsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewsUsecase(t mockConstructorTestingTNewNewsUsecase) *NewsUsecase {
	mock := &NewsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
