// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// NewsHandler is an autogenerated mock type for the NewsHandler type
type NewsHandler struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *NewsHandler) Get() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

type mockConstructorTestingTNewNewsHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewNewsHandler creates a new instance of NewsHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNewsHandler(t mockConstructorTestingTNewNewsHandler) *NewsHandler {
	mock := &NewsHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
